name: Audit

on:
  pull_request:
    branches: [ development, preprod, release ]

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm-audit
        uses: luisfontes19/npm-audit-action@v0.1.0

